This test is to show PYRO's remote exception capabilities.
The remote object contains various member functions which raise
various kinds of exceptions. The client will print those.

Note the special handling of the Pyro exception. 
It is possible to extract and print the *remote* traceback.
You can then see where in the code on the remote side the error occured!

Also try to set PYRO_DETAILED_TRACEBACK to 1 for a very detailed traceback!